spring:
  application:
    name: service-center

  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  jackson:
    serialization:
      write-dates-as-timestamps: false
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=3600s

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/